sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t luisnajera/docker-react -f Dockerfile.dev .

script:
    - docker run luisnajera/docker-react npm run test -- --coverage

